config/routes.rb
Rails.application.routes.draw do
   
  resources :words

  # default route to show basic angular stuff
  root 'angular#simple'

  get 'angular/simple'

  get 'chart/scatterplot'
  get ':controller/(:action)'
end

app/models/word.rb
class Word < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/angular_controller.rb
class AngularController < ApplicationController
  def demo
  end
  def simple
  end
  def behaviors
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper :all
  require 'json'
  before_filter  :run_before_filter

  def run_before_filter
    @params = params
    @con = params[:controller]
    @act = params[:action]
  #     puts "#{@con}##{@act}  <----------"
#     @serverIp = serverIp
  #     puts "\n\n","request_uri:  #{request.headers['REQUEST_URI']}"
  end
  def dumpDebug
    puts
    puts "+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +"
    puts
    puts "      request.headers['HTTP_ACCEPT']:  #{request.headers['HTTP_ACCEPT']}"
    puts "     request.headers['HTTP_REFERER']:  #{request.headers['HTTP_REFERER']}"
    puts "                 self.request.method:  #{request.method}"
    puts "                         request_uri:  #{request.headers['REQUEST_URI']}"
    puts "                   request.remote_ip:  #{request.remote_ip}"
#     puts "                           server ip:  #{@serverIp}"
  #     puts "                  request.user_agent:  #{request.user_agent}"
  #     puts "                          redirected:  #{@redirected}"
  #     puts "                  anybody_signed_in?:  #{anybody_signed_in?}"
  #     puts "                  devise_controller?:  #{devise_controller?}"
    puts "                   CONTROLLER (\@con):  #{params[:controller]}"
    puts "                       ACTION (\@act):  #{params[:action]}"
  #    puts "         params[:ajax]:  #{params[:ajax]?params[:ajax]:nil}"
  #    puts "           ajax header:  #{request.headers['HTTP_X_REQUESTED_WITH']}"
  #    puts "      @response_status:  #{@response_status}"
  #     dumpSession
    dumpParams
  #     dumpFlash
    puts "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
    puts
    puts
    puts
  end
  def serverIp
    orig, Socket.do_not_reverse_lookup = Socket.do_not_reverse_lookup, true  # turn off reverse DNS resolution temporarily
    UDPSocket.open do |s|
      s.connect '64.233.187.99', 1
      s.addr.last
    end
  ensure
    Socket.do_not_reverse_lookup = orig
  end
  def dumpSession
    puts "s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s"
    puts
    puts session.to_yaml
    puts
  end
  def dumpParams
    puts "p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p"
    puts
    puts 'params:'
    puts params.to_yaml
    puts
  end
  def dumpFlash
    puts "f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f"
    puts
    puts 'flash:'
    puts flash.to_yaml
    puts
  end
  ### include helpers
  # include ApplicationHelper

  ### handle some problems...
  # rescue_from ActionController::InvalidAuthenticityToken, 
  #   :with => Proc.new{
  #     flash[:other]='Bad Authenticity Token';puts '- '*30;puts "Bad Authenticity Token";puts request.inspect;puts '- '*30;:after_sign_in_path_for
  #   }
  # rescue_from ActionController::MethodNotAllowed, 
  #   :with => Proc.new{
  #     flash[:other]='Exception: Method Not Allowed';
  #     puts '- '*30;
  #     puts "Exception: Method Not Allowed", "#{request.headers['HTTP_X_REQUESTED_WITH']}", "#{request.headers['REQUEST_URI']}", "#{request.method}"; 
  #     puts '-'*40;
  #     puts request.inspect;
  #     puts '- '*30;
  #     redirect_to root_path
  #   }
  # rescue_from ActionController::RoutingError, 
  #   :with => Proc.new{
  #     flash[:error]='Exception: Routing error';
  #     puts '- '*30;
  #     puts "Exception: Routing Error "; 
  #     puts request.request_uri, "#{request.method}";
  #     puts '- '*30;
  #     redirect_to root_path
  #   }


  end

app/controllers/chart_controller.rb
class ChartController < ApplicationController
  def scatterplot
    `scripts/buildScatterplotData.sh`
  end
end

app/controllers/static_controller.rb
class StaticController < ActionController::Base
end

app/controllers/templates_controller.rb
class TemplatesController < ActionController::Base
  def simple
  end
  def simple_clicked
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @list = Word.all.to_a.sort_by.sort_by{|k|k['name'].downcase}
  end
  def create
    Word.create :name => params[:name]
    redirect_to words_path
  end
  def new
  end
  def edit
    @word = Word.find params['id']
  end
  def show
    @word = Word.find params['id']
  end
  def update
    Word.find(params['id']).update(:name => params['name'])
    redirect_to words_path
  end
  def destroy
    Word.find(params['id']).destroy
    redirect_to words_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/views/angular/simple.haml
%span.app.ng-cloak(ng:app='demo')
  .simple(ng:controller='SimpleInfoController as ctrlSimpleInfo' ng:init='ctrlSimpleInfo.init()')
    .triggerInfoPhase(ng:class='{infoOff : !triggerInfoPhase, infoOn : triggerInfoPhase}' ng:init='triggerInfoPhase = false' ng:mouseenter='triggerInfoPhase = true' ng:mouseleave='triggerInfoPhase = false')  
      mouseover this
    .info(ng:if='triggerInfoPhase')
      %h1.message
        {{ ctrlSimpleInfo.data.msg }}
      %ul.infoList
        %li.infoItem(ng:repeat='item in ctrlSimpleInfo.data.infoList | filter:search' class="{{item.name}}")
          %span.name.underline {{item.name}}
          %span.desc {{item.desc}}
  .right(ng:controller='CircleNestController as ctrlCircleNest' ui-view='simpleright')
    %div(ng:init='ctrlCircleNest.init()')
      #circleNest

app/views/angular/simple.slim
.app.row.ng-cloak ng:app='demo'
  .columns.large-12 ng:controller='SimpleInfoController as ctrlSimpleInfo' ng:init='ctrlSimpleInfo.init()'
    .row
      .triggerInfoPhase.columns.large-6 ng:class='{infoOff : !triggerInfoPhase, infoOn : triggerInfoPhase}' ng:init='triggerInfoPhase = false' ng:mouseenter='triggerInfoPhase = true' ng:mouseleave='triggerInfoPhase = false'
        = 'mouseover this'
      .columns.large-6 ng:controller='CircleNestController as ctrlCircleNest' ui-view='simpleright'
        div ng:init='ctrlCircleNest.init()'
          #circleNest
    .row
      .columns.large-12
        .info ng:if='triggerInfoPhase'
          h1.message 
            = '{{ ctrlSimpleInfo.data.msg }}'
          ul.infoList
            li.infoItem.row ng:repeat='item in ctrlSimpleInfo.data.infoList | filter:search' class="{{item.name}}"
              span.name.underline.columns.large-1.push-4
                = '{{item.name}}'
              span.desc.columns.large-3.pull-4 
                = '{{item.desc}}'

app/views/application/_app.haml
!!!
%html(lang="en" dir='ltr')
  %head
    = render(:partial=>'head')
  %body(id="#{@act}" class="#{@con}")
    #header
      = render(:partial=>'layouts/header')
    #content
      = yield
    = render(:partial=>'foot')
                      

app/views/application/_app.slim
doctype html
html lang="en" dir='ltr'
  head
    = render :partial => 'head'
  body id="#{@act}" class="#{@con}"
    #header.row
      .columns.large-12
        = render :partial => 'layouts/header'
    #content.row
      .columns.large-12
        = yield
    = render :partial => 'foot'
                      

app/views/application/_foot.haml
= javascript_include_tag 'application'

app/views/application/_foot.slim
= javascript_include_tag 'application'

app/views/application/_head.haml
%link(rel='shortcut icon' href='/favicon.ico')
%meta(charset='UTF-8')
%title 
  = "#{@con}"'#'"#{@act}"
= stylesheet_link_tag    'application', :media => 'all'

app/views/application/_head.slim
link rel='shortcut icon' href='/favicon.ico'
= csrf_meta_tag
meta charset='UTF-8'
title 
  = "#{@con}"'#'"#{@act}"
= stylesheet_link_tag    'application', :media => 'all'

app/views/chart/scatterplot.haml
%span.app.ng-cloak(ng:app='demo')
  %h1
    Interesting Scatterplot
  %h2
    Mouseover the dots to identify them. Refresh the page to see new data!
  %span.scatterPlot(ng:controller='ScatterplotController as ctrlScatterplot' ng:init='ctrlScatterplot.init()' ui-view='scatterplot')

app/views/chart/scatterplot.slim
.app.row.ng-cloak x-ng-app='demo'
  .scatterPlot.columns.large-12 x-ng-controller='ScatterplotController as ctrlScatterplot' x-ng-init='ctrlScatterplot.init()' ui-view='scatterplot'
    .row
      .title.columns.large-12
        h1 Interesting Scatterplot
    .row
      .description.columns.large-12
        h4 Mouseover the dots to identify them. Refresh the page to see new data!

app/views/layouts/_header.haml
%a(href='/angular/simple') simple Angular.js example
|
%a(href='/chart/scatterplot') chart/scatterplot

app/views/layouts/_header.slim
.navigation.row
  .columns.large-12
    .row
      .columns.large-4
        = link_to 'Behavior With Angular', angular_simple_path
      .columns.large-4
        = link_to 'D3 Scatterplot', chart_scatterplot_path
      .columns.large-4
        = link_to 'Very Basic REST Example', words_path

app/views/layouts/application.haml
- if "#{@con}##{@act}" == 'test#funcunit'
  = render(:partial=>'test')
- else
  = render(:partial=>'app')
  

app/views/layouts/application.slim
- if "#{@con}##{@act}" == 'test#funcunit'
  = render(:partial=>'test')
- else
  = render(:partial=>'app')
  

app/views/templates/ddd.haml
%div(ng:init='ctrl.init()')
  .right
    #circleNest

app/views/words/edit.slim
.word.edit.row
  .columns.large-12
    .title.row
      .columns.large-12
        h1 Edit Word 
    .form.row
      .columns.large-12
        form action="#{word_path(@word['id'])}" method="post" accept-charset='UTF-8'
          input type='hidden' name='authenticity_token' value="#{form_authenticity_token}"
          input type='hidden' name='_method' value="patch"
          input type='text' name='name' id='edit_word' value="#{@word['name']}"
          input type='submit' value='submit'
          label.hide for='edit_word' Edit Word Name

app/views/words/index.slim
.word.row
  .columns.large-12
    .title.row
      .columns.large-12
        h1 All Words
    .new.row
      .columns.large-12
        = link_to 'New Word', new_word_path
  .columns.large-12
    ul.list.row
      .columns.large-12
        - while @list.length > 0 do
          .word.row
            - wordColumns = 3
            - (0..wordColumns-1).each do
              - item = @list.shift
              li.word.columns class="large-#{12/wordColumns}"
                - if item
                  span 
                    = link_to item['name'], word_path(item['id'])
                - else
                  span &nbsp;

app/views/words/new.slim
.word.new.row
  .columns.large-12
    .title.row
      .columns.large-12
        h1 Create A New word 
    .form.row
      .columns.large-12
        form action="#{words_path}" method="post" accept-charset='UTF-8'
          input type='hidden' name='authenticity_token' value="#{form_authenticity_token}"
          input id='new_word' type='text' name='name'
          input type='submit' value='submit'
          word.hide for='new_word' New word Name

app/views/words/show.slim
.word.show.row
  .columns.large-12
    .title.row
      .columns.large-12
        h1 Showing The Word 
    .name.row
      .columns.large-12
        h2
          = @word['name']
    .ops.row
      .edit.columns.large-3.push-3
        = link_to 'Edit This Word', edit_word_path(@word['id'])
      .delete.columns.large-3.pull-3
        form action="#{word_path(@word['id'])}" method="post" accept-charset='UTF-8'
          input type='hidden' name='authenticity_token' value="#{form_authenticity_token}"
          input type='hidden' name='_method' value="delete"
          input.submit type='submit' value='Delete This Word'
          label.hide for='delete_word' Delete Word #{@word['name']}